const UNAUTHENTICATED = 403;
const RECORD_NOT_FOUND = 404;
const BAD_REQUEST = 400;
const CRASH_ERROR = 500;
const REQUEST_ERROR = 700;

export default {
  UNAUTHENTICATED,
  RECORD_NOT_FOUND,
  BAD_REQUEST,
  CRASH_ERROR,
  REQUEST_ERROR,
};
